using System.Text.Json.Serialization;

namespace HtmlCssToImage.Models.Requests;

/// <summary>
/// Represents common configuration options for creating an image using HTML/CSS or a URL.
/// This abstract class provides shared properties to define the rendering and processing behavior
/// for image generation requests.
/// </summary>
[JsonDerivedType(typeof(CreateHtmlCssImageRequest))]
[JsonDerivedType(typeof(CreateUrlImageRequest))]
public abstract class CreateImageCommonOptions:ICreateImageRequestBase
{
    /// <summary>
    /// A CSS selector to target a specific element on the page. The API will crop the image to the dimensions of this element.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/selector/">Read the selector Guide for more information.</see>
    /// </summary>
    public string? Selector { get; set; }

    /// <summary>
    /// Adjusts the pixel ratio for the screenshot. The default is 2 which is equivalent to a 4K monitor.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/device_scale/">Read the device_scale Guide for more information.</see>
    /// </summary>
    public double? DeviceScale { get; set; }

    /// <summary>
    /// Set the height of Chrome's viewport. This will disable automatic cropping.
    /// </summary>
    public uint? ViewportHeight { get; set; }

    /// <summary>
    /// Set the width of Chrome's viewport. This will disable automatic cropping.
    /// </summary>
    public uint? ViewportWidth { get; set; }

    /// <summary>
    /// Sets a limit on time to wait until the screenshot is taken. Use this if your page loads a lot of extra irrelevant content, and you want to reduce the render time.
    /// </summary>
    public uint? MaxWaitMs { get; set; }

    /// <summary>
    /// Adds extra time before taking the screenshot, like if you need to wait for Javascript to execute
    /// <see href="https://docs.htmlcsstoimage.com/parameters/ms_delay/">See the ms_delay docs for more information.</see>
    /// </summary>
    public uint? MsDelay { get; set; }

    /// <summary>
    /// This will wait until 'ScreenshotReady()' is called from Javascript to take the screenshot.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/render_when_ready/">Read the Render When Ready Guide for more information.</see>
    /// </summary>
    public bool? RenderWhenReady { get; set; }

    /// <summary>
    /// Ensure the image is only ever rendered and saved one time. This is an advanced option not applicable to most scenarios.
    /// </summary>
    public bool? MaxRenderOnce { get; set; }

    /// <summary>
    /// Reuse an identical image created within this many seconds without consuming image credits. HTML/CSS defaults vary by plan, while URL requests default to 0. Set to 0 to disable deduplication.
    /// This applies only to standard single-image POST creation requests. It does not apply to image batch requests and is not included in signed create-and-render URLs generated by the client.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/dedupe_duration_s/">Read the dedupe_duration_s documentation for more information.</see>
    /// </summary>
    public uint? DedupeDurationS { get; set; }

    /// <summary>
    /// Twemoji is used to render emoji as a fallback for native emoji fonts. This option will disable that behavior.
    /// </summary>
    public bool? DisableTwemoji { get; set; }

    /// <summary>
    /// Options for generating a PDF from the HTML/CSS.
    /// </summary>
    public PDFOptions? PDFOptions { get; set; }

    /// <summary>
    /// Set Chrome to render assuming the user has explicitly set their browser to Light or Dark mode.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/color_scheme/">Read the color_scheme Guide for more information.</see>        /// </summary>
    public ColorSchemeType? ColorScheme { get; set; }

    /// <summary>
    /// Sets the timezone for the browser instance. Use IANA timezone format (e.g. 'America/New_York').
    /// </summary>
    public string? Timezone { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the viewport should be rendered as if it's being viewed from a mobile device.
    /// </summary>
    public bool? ViewportMobile { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the viewport should be in landscape orientation.
    /// </summary>
    public bool? ViewportLandscape { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether touch interactions are enabled within the viewport.
    /// </summary>
    public bool? ViewportTouch { get; set; }

    /// <summary>
    /// Gets or sets the media type to use for rendering.
    /// </summary>
    public MediaType? MediaType { get; set; }

    /// <summary>
    /// Gets or sets the proxy ID to use for rendering.
    /// <see href="https://docs.htmlcsstoimage.com/guides/advanced/proxies/">Read the Proxy Guide for more information.</see>
    /// </summary>
    public string? ProxyId { get; set; }

    /// <summary>
    /// Gets or sets the storage destination ID where rendered images should be saved.
    /// <see href="https://docs.htmlcsstoimage.com/guides/advanced/storage-destinations/">Read the Storage Destinations Guide for more information.</see>
    /// </summary>
    public string? StorageDestinationId { get; set; }

    /// <summary>
    /// Gets or sets the maximum width of the rendered image in jumbo mode. Consumes additional image credits, requires <see cref="JumboMaxHeight"/> to be defined as well.
    /// <see href="https://docs.htmlcsstoimage.com/guides/advanced/jumbo-images/"> Read the Jumbo Images Guide for more information.</see>
    /// </summary>
    public uint? JumboMaxWidth { get; set; }

    /// <summary>
    /// Gets or sets the maximum height of the rendered image in jumbo mode. Consumes additional image credits, requires <see cref="JumboMaxWidth"/> to be defined as well.
    /// <see href="https://docs.htmlcsstoimage.com/guides/advanced/jumbo-images/"> Read the Jumbo Images Guide for more information.</see>
    /// </summary>
    public uint? JumboMaxHeight { get; set; }

    /// <summary>
    /// Gets or sets whether the image should be rendered with a transparent background.
    /// <see href="https://docs.htmlcsstoimage.com/parameters/transparent_background/">Read the transparent_background Guide for more information.</see>
    /// </summary>
    public bool? TransparentBackground { get; set; }


    /// <inheritdoc />
    public RenderImageFormat? Format { get; set; }
}
